version: 2
jobs:
  build:
    working_directory: /go/src/github.com/marcopollivier/dio-expert-session-pre-class
    environment:
      TEST_RESULTS: /tmp/test-results
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go vet ./...
      - run: go test ./...